import * as Crypto from "expo-crypto";

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";

function base64ToBase64Url(base64Value: string): string {
  // Convert normal base64 into URL-safe base64 required by PKCE.
  return base64Value.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

/**
 * Creates a high-entropy PKCE verifier string.
 * Input: desired length (default 64).
 * Output: random verifier string using PKCE-valid characters.
 */
export function generateCodeVerifier(length = 64): string {
  // Verifier is a high-entropy random string generated by the public client.
  const bytes = Crypto.getRandomBytes(length);
  return Array.from(bytes)
    .map((byte) => ALPHABET[byte % ALPHABET.length])
    .join("");
}

/**
 * Creates PKCE challenge from verifier.
 * Input: verifier string.
 * Output: BASE64URL(SHA256(verifier)).
 */
export async function generateCodeChallenge(codeVerifier: string): Promise<string> {
  // Challenge = BASE64URL(SHA256(code_verifier)).
  const digest = await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, codeVerifier, {
    encoding: Crypto.CryptoEncoding.BASE64,
  });
  return base64ToBase64Url(digest);
}
